[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
eframe = "0.17"
reqwest = { version = "0.11", features = ["json", "blocking"] }
serde = "1.0"
ws = "0.9"
